# Используем образ линукс Alpine с версией node 14
FROM node:20.15.1-alpine

# Указываем нашу рабочую директорию
WORKDIR /web-api

# Скорировать package.json и package-lock.json внутрь контейнера
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем оставшиеся приложения в контейнер
COPY . . 

# Открыть порт в нашем контейнер
EXPOSE $PORT

# Запускаем наш сервер
CMD ["npm", "start"]

VOLUME /web-api