/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/inbox`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/../tabs/tasks/TaskDescriptionTab`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(projects)'}/create` | `/create`; params?: Router.UnknownInputParams; } | { pathname: `${'/(projects)'}/projects` | `/projects`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tasks)'}/create` | `/create`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tasks)'}/tasks` | `/tasks`; params?: Router.UnknownInputParams; } | { pathname: `${'/(projects)'}/[project_id]` | `/[project_id]`, params: Router.UnknownInputParams & { project_id: string | number; } } | { pathname: `${'/(tasks)'}/[task_id]` | `/[task_id]`, params: Router.UnknownInputParams & { task_id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/inbox`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/../tabs/tasks/TaskDescriptionTab`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(projects)'}/create` | `/create`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(projects)'}/projects` | `/projects`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tasks)'}/create` | `/create`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tasks)'}/tasks` | `/tasks`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(projects)'}/[project_id]` | `/[project_id]`, params: Router.UnknownOutputParams & { project_id: string; } } | { pathname: `${'/(tasks)'}/[task_id]` | `/[task_id]`, params: Router.UnknownOutputParams & { task_id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/inbox${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/../tabs/tasks/TaskDescriptionTab${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `${'/(projects)'}/create${`?${string}` | `#${string}` | ''}` | `/create${`?${string}` | `#${string}` | ''}` | `${'/(projects)'}/projects${`?${string}` | `#${string}` | ''}` | `/projects${`?${string}` | `#${string}` | ''}` | `${'/(tasks)'}/create${`?${string}` | `#${string}` | ''}` | `/create${`?${string}` | `#${string}` | ''}` | `${'/(tasks)'}/tasks${`?${string}` | `#${string}` | ''}` | `/tasks${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/inbox`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/../tabs/tasks/TaskDescriptionTab`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(projects)'}/create` | `/create`; params?: Router.UnknownInputParams; } | { pathname: `${'/(projects)'}/projects` | `/projects`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tasks)'}/create` | `/create`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tasks)'}/tasks` | `/tasks`; params?: Router.UnknownInputParams; } | `${'/(projects)'}/${Router.SingleRoutePart<T>}` | `/${Router.SingleRoutePart<T>}` | `${'/(tasks)'}/${Router.SingleRoutePart<T>}` | `/${Router.SingleRoutePart<T>}` | { pathname: `${'/(projects)'}/[project_id]` | `/[project_id]`, params: Router.UnknownInputParams & { project_id: string | number; } } | { pathname: `${'/(tasks)'}/[task_id]` | `/[task_id]`, params: Router.UnknownInputParams & { task_id: string | number; } };
    }
  }
}
